project:
  type: website

website:
  title: "Mongolia 100"
  navbar:
    left:
      - href: all-games.qmd
        text: All Games
      - href: index.qmd
        text: Game
      - href: about.qmd
        text: Facts

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: false
